AWSRegion: "ca-central-1"
CognitoClientID: ""
CognitoPoolID: ""
CognitoRegion: ""
GraphqlURI: "http://10.0.1.9:4000/"
S3Bucket: "gdps-fs-sum-dwnld"
S3FilePrefix: "reports"
SsmPath: "gdps-fs-sum-dwnld"
Stage: "prod"